#config
Form-Title: "Welcome!"
Submit-Msg: "Submit"
Form-Content: "Welcome"
Btn1: "Rules"

UseFormInsteadOfChat: true
# set to false if you want to use chat instead of form as welcoming..

# Values for welcome message:
# {player} - gives player name
# {server} - gives server name
WelcomeMessage: "Hey! {player} has just joined {server}. Please welcome him!"
# When the player arrives on the server for the first time

#Join Message Values:
# {player} - gives player name
# {server} - gives server name
JoinMessage: "{player} is back! Have fun on {server}!"
#  When the player joins the server more than once
# if the UseFormInsteadOfChat is false then this will show instead of form


# Leave Message Values:
# {player} - gives player name

LeaveMessage: "{player} Has left the server"

LeaveMessageEnabled: true
